@startuml

left to right direction

rectangle "传统MJPEG方案" {

    [Camera]
    [HTTP轮询]
    [Base64编码]
    [Browser]

    Camera --> HTTP轮询
    HTTP轮询 --> Base64编码
    Base64编码 --> Browser
}

rectangle "本系统方案" {

    [RK3568]
    [二进制封包]
    [WebSocket]
    [createImageBitmap]
    [Canvas]

    RK3568 --> 二进制封包
    二进制封包 --> WebSocket
    WebSocket --> createImageBitmap
    createImageBitmap --> Canvas
}

note bottom

MJPEG:
轮询请求频繁
Base64增加33%体积
延迟约200ms+

本系统:
二进制传输
无Base64开销
端到端延迟<20ms

end note

@enduml